import {
  defineNuxtModule,
  addPlugin,
  addTemplate,
  createResolver
} from '@nuxt/kit';

export interface ModuleOptions {}

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: 'nuxt-uikit3',
    configKey: 'uikit3'
  },

  defaults: {},

  setup(options, nuxt) {
    const resolver = createResolver(import.meta.url);

    nuxt.hooks.hook('prepare:types', ({ references }) => {
      references.push({
        path: resolver.resolve(nuxt.options.buildDir, 'nuxt-uikit3.d.ts')
      });
    });

    addTemplate({
      filename: 'nuxt-uikit3.d.ts',
      getContents: () => {
        return `// Generated by nuxt-uikit3
        import UIkit from 'uikit';

        declare module '#app' {
          interface NuxtApp {
            $uikit: typeof UIkit;
          }
        }
        `;
      }
    });

    addPlugin({ src: resolver.resolve('./runtime/plugin'), mode: 'client' });
  }
});
