import type { NuxtUIkitModuleOptions } from './types';
import {
  defineNuxtModule,
  addPlugin,
  addTemplate,
  createResolver
} from '@nuxt/kit';

export default defineNuxtModule<NuxtUIkitModuleOptions>({
  meta: {
    name: 'nuxt-uikit3',
    configKey: 'uikit',
    compatibility: {
      nuxt: '^3.0.0',
      bridge: false
    }
  },

  defaults: {
    css: {
      coreCss: true,
      coreTheme: true
    },
    js: true,
    icons: true
  },

  async setup(options, nuxt) {
    const resolver = createResolver(import.meta.url);

    addTemplate({
      filename: 'nuxt-uikit3.d.ts',
      getContents: () => {
        return `// Generated by nuxt-uikit3
        import UIkit from 'uikit';

        declare module 'uikit' {
          import UIkit from 'uikit';
          export default UIkit;
        }

        declare module '#app' {
          interface NuxtApp {
            $uikit: typeof UIkit;
          }
        }
        `;
      }
    });

    nuxt.options.runtimeConfig.app.uikit ||= {} as NuxtUIkitModuleOptions;
    nuxt.options.runtimeConfig.app.uikit = options;

    const cssOptions = options.css;

    if (cssOptions?.coreCss && cssOptions.coreTheme) {
      nuxt.options.css ||= [];
      nuxt.options.css.push(`uikit/dist/css/uikit.min.css`);
    }

    if (options.css?.coreCss && !cssOptions?.coreTheme) {
      nuxt.options.css ||= [];
      nuxt.options.css.push(`uikit/dist/css/uikit-core.css`);
    }

    nuxt.options.build.transpile.push(resolver.resolve('./runtime'));

    addPlugin({
      src: resolver.resolve('./runtime/plugin.client'),
      mode: 'client'
    });
  }
});
